Account screen created with logout ability
Veryable/veryable-cc-android pull request #13
Opened 2022-05-20 19:02 UTC by Prashantjagwani

@moretanjames Could you review the PR.
I have tested the theme change and logout feature.
There might be ui rendering issue as per the device I tested.

2022-05-20 21:05 UTC, moretanjames requested changes
Pretty good overall.

2022-05-23 17:49 UTC, Prashantjagwani commented
Hey @moretanjames ,
Could you review the changes. I have added the error layout and shimmer view for the screen. Also update user district and fetch user district api are implemented now. 🤘🏻

2022-05-23 19:36 UTC, moretanjames requested changes
Sorry about this

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/features/account/AccountFragment.kt
> +    fun showDistrictSelectorDialog(list: List<District>) {
Could be private. Also instead of passing a reference to a list around, we should use the version stored in `viewModel.districtsLiveData.value`

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/features/account/AccountFragment.kt
> +                .setTitle("Select District")
Strings should be in the strings.xml file

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/features/account/AccountViewModel.kt
> +    fun logout() = liveData {
I think logout should live in MainViewModel. It can still look Mostly like this but then you wouldn't have to post to the applaunchstate from the fragment and that could all be contained within the viewmodel

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/features/account/AccountViewModel.kt
> +    val accountStateEvent = MutableLiveData<AccountState>()
Since this is a live data and not a Live Event lets rename this variable to reflect that for readablility

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/features/main/MainActivity.kt
> +    fun updateFragment(fragment: Fragment) {
Lets name this addFragmentToBackStack instead because that will better reflect what we are actually doing

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/models/account/UserDistrict.kt
> +    val operatorId: Int? = null,
Are these fields actually nullable?

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/repos/app/AppRepo.kt
> +    suspend fun getUserData(): UserData? {
This function is never called. Please remove it

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/repos/districts/DistrictsApiService.kt
> +    suspend fun getDefaultDistrict(@Path("user-id") userId: Int?): Response<UserDistrict>
Can we rename everything that says "Default District" to say "Operator App District". I think otherwise we are going to get confused about what they are. In fact, in the app we are going to call it "Operator App District" regardless of what the designs say because the designer didn't understand the difference when he made the designs

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/repos/districts/DistrictsRepo.kt
> +    suspend fun fetchDefaultDistrict(userId: Int?): UserDistrict? {
Same comment about the naming convention.

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/repos/districts/DistrictsRepo.kt
> +        }.getOrNull().let {
Its fine if you dont want to use the .getNetworkResponse or the .recordParsingErrors extension function, but you should be recording parsing errors some how.

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/repos/districts/DistrictsRepo.kt
> +        return runCatching {
Same two comments as above

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/utils/AlertUtils.kt
> +class AlertUtils {
Excellent addition

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/res/layout/fragment_account.xml
> +                    android:id="@+id/password_edit_btn"
If you are going to continue with this particular way of creating a text style button, please add a way to see a ripple on click. I would recommend switching to method 3 tho.

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/res/layout/fragment_account.xml
> +                    android:id="@+id/password_edit_btn"
This applys for all three of these text buttons on the screen

2022-05-23 19:36 UTC, moretanjames commented on app/src/main/res/values/strings.xml
> +    <string name="skeleton_small_text">Lorem</string>
These skelton and place holder strings should be in the untranslated_strings.xml file

2022-05-23 22:04 UTC, Prashantjagwani commented
Hey @moretanjames ,
I have done all the changes mentioned in the comments.
Model view logic change, network error handling, text button ui changes, renamed confusing variables.

2022-05-24 16:48 UTC, Prashantjagwani commented on app/src/main/java/com/veryableops/commandcenter/features/main/MainViewModel.kt
> +    val appStateEvent = SingleLiveEvent(AppState())
Remove this logic not needed anymore.

2022-05-24 16:48 UTC, Prashantjagwani commented on app/src/main/res/drawable/rectangle_outline_blue_light_blue_90.xml
> +        android:color="?attr/colorPrimary" />
Removed file.

2022-05-24 16:49 UTC, Prashantjagwani commented on app/src/main/res/layout/fragment_account.xml
> +                    android:id="@+id/password_edit_btn"
Used the 3rd method with the loading button.

2022-05-24 16:50 UTC, Prashantjagwani commented on app/src/main/java/com/veryableops/commandcenter/features/account/AccountFragment.kt
> +                .setTitle("Select District")
Added string to string.xml.

2022-05-24 16:50 UTC, Prashantjagwani commented on app/src/main/java/com/veryableops/commandcenter/features/account/AccountViewModel.kt
> +    fun logout() = liveData {
Moved logout to MainViewModel.

2022-05-24 16:50 UTC, Prashantjagwani commented on app/src/main/java/com/veryableops/commandcenter/features/account/AccountViewModel.kt
> +    val accountStateEvent = MutableLiveData<AccountState>()
Renamed.

2022-05-24 16:54 UTC, Prashantjagwani commented on app/src/main/res/values/strings.xml
> +    <string name="skeleton_small_text">Lorem</string>
Moved the skeleton text to untranslated_strings.xml

2022-05-24 18:56 UTC, poojakaluskar requested changes
Looks good overall. Few things from my side.

Also, the version number doesn't show up on my phone so can you look into that?

2022-05-24 18:56 UTC, poojakaluskar commented on app/src/main/res/layout/fragment_account.xml
> +                    android:text="@string/edit"
Setting the text here doesn't have any effects so let's remove it for now.

Also, according to designs, the buttons are aligned right/end of the view and we cannot achieve that using the `LoadingButton` that we migrated since it has the standard Material Button component padding around it. To override that, you'll have to use the standard Button component here.

I'll update the Button component in the Business app to make sure we are able to do this in the future using the custom button.

2022-05-24 18:56 UTC, poojakaluskar commented on app/src/main/res/layout/fragment_account.xml
> +                    android:text="@string/edit"
Same comment about previous button.

2022-05-24 18:56 UTC, poojakaluskar commented on app/src/main/java/com/veryableops/commandcenter/utils/AlertUtils.kt
> +        fun showSnackBar(view: View, @StringRes text: Int) {
This is not used right now. When do you think we'll need it and can we live without it for now?

2022-05-24 18:56 UTC, poojakaluskar commented on app/src/main/java/com/veryableops/commandcenter/features/account/AccountFragment.kt
> +                        .setNegativeButton("Cancel") { dialog, _ ->
Can you add "Cancel" String in the xml?

2022-05-24 18:56 UTC, poojakaluskar commented on app/src/main/java/com/veryableops/commandcenter/features/account/AccountFragment.kt
> +    fun showDistrictSelectorDialog() {
Can this method be private?

2022-05-24 18:56 UTC, poojakaluskar commented on app/src/main/res/layout/fragment_account.xml
> +                    android:layout_marginTop="8dp"
The spacing is too much between the Password title and this view. Doesn't look good according to the designs.

2022-05-24 18:56 UTC, poojakaluskar commented on app/src/main/res/layout/fragment_account.xml
> +                    android:textSize="22sp"
You don't need text size if you are already using the text style. The text styles are already mapped according to the style guide so we don't need to override those.

2022-05-24 18:56 UTC, poojakaluskar commented on app/src/main/res/layout/fragment_account.xml
> +                android:paddingStart="20dp"
Can we use the standard 16dp margin/padding that we are using (or should be using) in the entire app?

2022-05-24 20:07 UTC, Prashantjagwani commented on app/src/main/java/com/veryableops/commandcenter/utils/AlertUtils.kt
> +        fun showSnackBar(view: View, @StringRes text: Int) {
Yes, It will be used later on. I will remove it for now.

2022-05-24 20:41 UTC, Prashantjagwani commented on app/src/main/res/layout/fragment_account.xml
> +            android:textSize="12sp" />
Changed it to "Caption" style.

2022-05-24 20:42 UTC, Prashantjagwani commented on app/src/main/res/layout/fragment_account.xml
> +                    android:text="@string/edit"
Changed the button to material button.

2022-05-24 20:42 UTC, Prashantjagwani commented on app/src/main/res/layout/fragment_account.xml
> +                    android:text="@string/edit"
Changed the button to material button.

2022-05-24 20:42 UTC, Prashantjagwani commented on app/src/main/java/com/veryableops/commandcenter/features/account/AccountFragment.kt
> +                        .setNegativeButton("Cancel") { dialog, _ ->
Roger that.

2022-05-24 20:42 UTC, Prashantjagwani commented on app/src/main/java/com/veryableops/commandcenter/features/account/AccountFragment.kt
> +    fun showDistrictSelectorDialog() {
Done

2022-05-24 20:43 UTC, Prashantjagwani commented on app/src/main/res/layout/fragment_account.xml
> +                    android:layout_marginTop="8dp"
Changed it to 4dp.

2022-05-24 20:43 UTC, Prashantjagwani commented on app/src/main/res/layout/fragment_account.xml
> +                    android:textSize="22sp"
changed the style to Headline3 and removed the text size

2022-05-24 20:43 UTC, Prashantjagwani commented on app/src/main/res/layout/fragment_account.xml
> +                android:paddingStart="20dp"
Done. Changed for the whole screen.

2022-05-24 20:44 UTC, Prashantjagwani commented
Hey @poojakaluskar 
Could you review the changes..🙂

2022-05-24 21:40 UTC, Prashantjagwani commented
Hey @poojakaluskar 
Finally edit button is fixed 🙏🏻

2022-05-24 21:43 UTC, poojakaluskar approved these changes

2022-05-24 21:45 UTC, merged