Update password ui created and viewmodel setup
Veryable/veryable-cc-android pull request #16
Opened 2022-05-24 16:42 UTC by Prashantjagwani

Hey @poojakaluskar , Could you review this PR
- created the ui for update password
- viewmodel setup with the api request
- created repo and req model for the update password request

2022-05-24 22:31 UTC, poojakaluskar requested changes
Still reviewing but wanted to add comments before I leave. I'll pick it up tomorrow.

2022-05-24 22:31 UTC, poojakaluskar commented on app/src/main/java/com/veryableops/commandcenter/features/password/UpdatePasswordFragment.kt
> +        binding.cancelButton.setActionButton(getString(R.string.cancel), true, ButtonType.PRIMARY, ButtonStyle.OUTLINED)
The cancel button doesn't have a click listener?

2022-05-24 22:31 UTC, poojakaluskar commented on app/src/main/java/com/veryableops/commandcenter/features/password/UpdatePasswordFragment.kt
> +        binding.saveButton.setActionButton(getString(R.string.save), false, ButtonType.PRIMARY, ButtonStyle.CONTAINED)
Since there are default values set for the Button for type, style and disability, you don't have to pass the values unless you are overriding the default values.

2022-05-24 22:31 UTC, poojakaluskar commented on app/src/main/java/com/veryableops/commandcenter/features/password/UpdatePasswordViewModel.kt
> +    var passwordLiveData = MutableLiveData("")
What value are we getting with LiveData variables here if we are not using the data binding? 

Right now, you are setting the live data value on text change and then also observing the live data value change which I feel can be simplified by eliminating LiveData parameters here unless I am missing something.

2022-05-24 22:31 UTC, poojakaluskar commented on app/src/main/java/com/veryableops/commandcenter/features/password/UpdatePasswordFragment.kt
> +            Utils.getThemeAttrColor(
`Utils.getThemeAttrColor(
                requireContext(),
                if (doesPasswordMatch(password, Cons.REGEX_PASS_UPPERCASE))
                    R.attr.colorPrimaryText
                else R.attr.colorOnBackgrounds
            )`
            
           
Can this be its own method since you are writing the same code 5 times?  Imagine we decided to change the color and now you have to do that 5 different times.

2022-05-25 15:07 UTC, Prashantjagwani commented on app/src/main/java/com/veryableops/commandcenter/features/password/UpdatePasswordFragment.kt
> +        binding.saveButton.setActionButton(getString(R.string.save), false, ButtonType.PRIMARY, ButtonStyle.CONTAINED)
removed the values similar to default values

2022-05-25 15:09 UTC, Prashantjagwani commented on app/src/main/java/com/veryableops/commandcenter/features/password/UpdatePasswordViewModel.kt
> +    var passwordLiveData = MutableLiveData("")
I wasn't sure whether we can do data binding in the project. Removed the live data observer and using the view directly for the text changes.

2022-05-26 14:23 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/features/password/UpdatePasswordFragment.kt
> +            binding.newPassText.text?.isNotBlank() ?: false && binding.confirmPassText.text?.isNotBlank() ?: false &&
instead of `?.isNotBlank() ?: false` you could do `!binding.newPassText.text.isNullOrBlank()`

2022-05-26 14:34 UTC, moretanjames commented on app/src/main/java/com/veryableops/commandcenter/utils/Cons.kt
> +class Cons {
Instead of a class with a companion object, lets make this class just an object. Also lets call the class Const or Constants.

2022-05-26 16:05 UTC, Prashantjagwani commented on app/src/main/java/com/veryableops/commandcenter/utils/Cons.kt
> +class Cons {
Roger that!

2022-05-26 16:06 UTC, Prashantjagwani commented on app/src/main/java/com/veryableops/commandcenter/utils/VryPasswordUtils.kt
> +class VryPasswordUtils {
Same comment as above. 😅

2022-05-26 16:15 UTC, moretanjames approved these changes
Looks Slick

2022-05-26 16:16 UTC, merged